version: "3"
services:
  sdlit-rproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "sdlit-rproxy-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${db_user}"
      DB_MYSQL_PASSWORD: "${db_pass}"
      DB_MYSQL_NAME: "${db_name}"
      DISABLE_IPV6: 'true'
    volumes:
      - /non-shared/sdlit-rproxy/data:/data
      - /non-shared/sdlit-rproxy/letsencrypt:/etc/letsencrypt
    depends_on:
      - sdlit-rproxy-db

  sdlit-rproxy-db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${db_root}"
      MYSQL_DATABASE: "${db_name}"
      MYSQL_USER: "${db_user}"
      MYSQL_PASSWORD: "${db_pass}"
    volumes:
      - /non-shared/sdlit-rproxy/mysql:/var/lib/mysql